debug: false

server:
  port: ${API_PORT}
  forward-headers-strategy: native

spring:
  codec.max-in-memory-size: "2MB"

  webflux:
    base-path: "/api"

  r2dbc:
    username: ${POSTGRES_USERNAME}
    name: ${POSTGRES_DATABASE}
    password: ${POSTGRES_PASSWORD}
    url: "r2dbc:postgres://${POSTGRES_HOST}"

  rsocket:
    server:
      mapping-path: "/gateway"
      transport: websocket

  security.oauth2.client.registration:
    google:
      client-id: "${GOOGLE_CLIENT_ID}"
      client-secret: "${GOOGLE_CLIENT_SECRET}"
