debug: false

server:
  port: ${API_PORT}
  forward-headers-strategy: native

spring:
  webflux:
    base-path: "/api"

  r2dbc:
    username: ${POSTGRES_USERNAME}
    name: ${POSTGRES_DATABASE}
    password: ${POSTGRES_PASSWORD}
    url: "r2dbc:postgres://${POSTGRES_HOST}"

google.recaptcha.secret: ${GOOGLE_RECAPTCHA_SECRET}
